language: php

sudo: false

php:
  - 7.0
  - 7.1
  - 7.2
  - master

before_install:
  - composer self-update
  - composer clear-cache

install:
  - make install

script:
  - make coverage

after_success:
  - bash <(curl -s https://codecov.io/bash)
